### PR TITLE
Added an example

### PR DESCRIPTION
**Pull request by adwelly**
The diamond kata - see the comments for details.

### CODE REVIEW

**Comment by jduey** [comment]
That is awesome. You're really on the bleeding edge trying to code with things in this state. :)

Would you mind replacing 'list-concat' with 'comp'? I would like to establish the idiom of always using the protocol functions instead of the implementation specific ones where possible.

Also, I think 'print-all' is just '(map s println)', right?

Great work! It's exciting to see someone else doing something with Toccata.

**Comment by adwelly** [comment]
Actually I tried (map  println ...) first and that threw a couple of
complaints about flat map - from memory - I'm AFK at the moment. I'm happy
to use comp instead of list-concat, but it composes two functions yes? How
does it concat sequences?

I don't know if you would be curious to see the original  - there's a few
differences from Clojure. are you planning to be Clojure inspired or as
faithful as possible to the ancestor languages?

**Comment by jduey** [comment]
Ah yes. It should be

(map (diamond "C") println)

The order of the args is reversed for map from Clojure so it can
dispatch on the type being mapped over.

Just being Clojure inspired. There were too many 'tweaks' I wanted to
make to call it Clojure.

**Comment by adwelly** [comment]
That's interesting. Are there implications for transducers? Will there be transducers? actually I'm hoping there will be something like core.async more as I hope that they will help with real world things like events from drivers, interrupts and so on.

Still, early days. Can you make the final corrections or do you need me to do it?

**Comment by jduey** [comment]
Go ahead and make them, please.

**Comment by adwelly** [comment]
Those changes are now made and pushed to my fork.

**Comment by jduey** [comment]
Thanks!

**Pull request merged**
